### ISSUE TITLE
Ubuntu 16.04 compile error

### ISSUE THREAD

**Issue by hoyanf** [edollar-project/edollar#1]
Compiled on Ubuntu encountered the following error :-

[ 96%] Linking CXX executable ../../bin/edollard
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-ctx.o): In function `zmq::ctx_t::~ctx_t()':
(.text+0xfa6): undefined reference to `randombytes_close'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-zmq_utils.o): In function `zmq_curve_keypair':
(.text+0x337): undefined reference to `crypto_box_keypair'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::encode(zmq::msg_t*)':
(.text+0x176): undefined reference to `crypto_box_afternm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::decode(zmq::msg_t*)':
(.text+0x4ab): undefined reference to `crypto_box_open_afternm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::curve_client_t(zmq::options_t const&)':
(.text+0x87e): undefined reference to `sodium_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::curve_client_t(zmq::options_t const&)':
(.text+0x89a): undefined reference to `crypto_box_keypair'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_hello(zmq::msg_t*)':
(.text+0xb9a): undefined reference to `crypto_box'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::process_welcome(unsigned char const*, unsigned long)':
(.text+0xe25): undefined reference to `crypto_box_open'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::process_welcome(unsigned char const*, unsigned long)':
(.text+0xf17): undefined reference to `crypto_box_beforenm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
(.text+0x108a): undefined reference to `randombytes'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
(.text+0x10ae): undefined reference to `crypto_box'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::produce_initiate(zmq::msg_t*)':
(.text+0x12b3): undefined reference to `crypto_box'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_client.o): In function `zmq::curve_client_t::process_ready(unsigned char const*, unsigned long)':
(.text+0x15e0): undefined reference to `crypto_box_open_afternm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::encode(zmq::msg_t*)':
(.text+0x176): undefined reference to `crypto_box_afternm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::decode(zmq::msg_t*)':
(.text+0x5bb): undefined reference to `crypto_box_open_afternm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::curve_server_t(zmq::session_base_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, zmq::options_t const&)':
(.text+0x959): undefined reference to `sodium_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::curve_server_t(zmq::session_base_t*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, zmq::options_t const&)':
(.text+0x975): undefined reference to `crypto_box_keypair'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_hello(zmq::msg_t*)':
(.text+0xdc6): undefined reference to `crypto_box_open'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
(.text+0xeed): undefined reference to `randombytes'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
(.text+0xf81): undefined reference to `randombytes'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
(.text+0xf9e): undefined reference to `crypto_secretbox'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
(.text+0xfc4): undefined reference to `randombytes'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_welcome(zmq::msg_t*)':
(.text+0x10fb): undefined reference to `crypto_box'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::produce_ready(zmq::msg_t*)':
(.text+0x13b1): undefined reference to `crypto_box_afternm'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
(.text+0x231e): undefined reference to `crypto_secretbox_open'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
(.text+0x2400): undefined reference to `crypto_box_open'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
(.text+0x2513): undefined reference to `crypto_box_open'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libzmq.a(libzmq_la-curve_server.o): In function `zmq::curve_server_t::process_initiate(zmq::msg_t*)':
(.text+0x254a): undefined reference to `crypto_box_beforenm'
collect2: error: ld returned 1 exit status
src/daemon/CMakeFiles/daemon.dir/build.make:271: recipe for target 'bin/edollard' failed
make[3]: *** [bin/edollard] Error 1
make[3]: Leaving directory '/home/mm-miner/Downloads/miner/edollar/build/release'
CMakeFiles/Makefile2:2381: recipe for target 'src/daemon/CMakeFiles/daemon.dir/all' failed
make[2]: *** [src/daemon/CMakeFiles/daemon.dir/all] Error 2
make[2]: Leaving directory '/home/mm-miner/Downloads/miner/edollar/build/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/mm-miner/Downloads/miner/edollar/build/release'
Makefile:62: recipe for target 'release-all' failed
make: *** [release-all] Error 2

```
uname -a
Linux miner 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
```

**Comment by edollar-project** [comment]
That compile logs show that you didn't install libzmq, 
Try install zqm by `sudo apt-get install liblzma-dev`

**Comment by amelora** [comment]
I have the same issue and it doesn't seem to be the cause as it's already installed on my computer.

"sudo apt install liblzma-dev" returns:
liblzma-dev is already the newest version (5.1.1alpha+20120614-2ubuntu2)

I also tried on another computer on which I had to install almost all dependencies and I got the same result.

**Comment by paulie-g** [comment]
think that was a typo (liblzma is a compression algo library), the library you need is libzmq (the zeroMQ message queue)

**Comment by edollar-project** [comment]
Oh yes. I didnt realize that. Try install zeromq.

Thanks.

Vào 23-01-2018 08:33, "Paul G" <notifications@github.com> đã viết:

**Comment by edollar-project** [comment]
Yes, It's a typo mistake.
Try installing zeromq
`sudo apt-get install libzmq3-dev`
